//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.Admin.Api.Dao.User {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal UserDaoResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.Admin.Api.Dao.User.UserDaoResources", typeof(UserDaoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to INSERT INTO user
        ///(`firstname`,
        ///`lastname`,
        ///`email`,
        ///`global_admin`)
        ///VALUES
        ///(@firstname,
        ///@lastname,
        ///@email,
        ///@global_admin) ON DUPLICATE KEY UPDATE firstname=@firstname, lastname=@lastname,global_admin=@global_admin,id=LAST_INSERT_ID(id);
        ///SELECT LAST_INSERT_ID();.
        /// </summary>
        public static string InsertUser {
            get {
                return ResourceManager.GetString("InsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT d.id as domain_id, d.name as domain_name 
        ///FROM derived_user_domain_rollup_permissions p
        ///JOIN derived_domain_tree dt ON dt.parent_id = p.domain_id
        ///JOIN domain d on d.id = dt.child_id
        ///WHERE (d.monitor = 1 OR d.publish = 1) AND p.user_id = @userId;.
        /// </summary>
        public static string SelectDomainPermissions {
            get {
                return ResourceManager.GetString("SelectDomainPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT u.id, u.firstname, u.lastname, u.email, u.global_admin
        ///FROM user u
        ///WHERE u.email = @email;.
        /// </summary>
        public static string SelectUserByEmail {
            get {
                return ResourceManager.GetString("SelectUserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT u.id, u.firstname, u.lastname, u.email, u.global_admin
        ///FROM user u
        ///WHERE u.id = @id;.
        /// </summary>
        public static string SelectUserById {
            get {
                return ResourceManager.GetString("SelectUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  SELECT 
        ///u.id, 
        ///u.firstname,
        ///u.lastname,
        ///u.email,
        ///u.global_admin
        ///FROM user u
        ///JOIN group_user_mapping gum ON u.id = gum.user_id
        ///JOIN `group` g on g.id  = gum.group_id
        ///JOIN group_domain_mapping gdm on g.id  = gdm.group_id
        ///JOIN domain d on d.id  = gdm.domain_id
        ///WHERE d.id = @domainId
        ///AND (@search IS NULL 
        ///	OR LOWER(u.firstname) LIKE CONCAT(LOWER(@search), &apos;%&apos;)
        ///	OR LOWER(u.lastname) LIKE CONCAT(LOWER(@search), &apos;%&apos;)
        ///	OR LOWER(u.email) LIKE CONCAT(&apos;%&apos;, LOWER(@search), &apos;%&apos;))
        ///ORDER BY u.email
        ///LIMIT  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectUsersByDomainId {
            get {
                return ResourceManager.GetString("SelectUsersByDomainId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  SELECT 
        ///u1.id,
        ///u1.firstname,
        ///u1.lastname,
        ///u1.email,
        ///u1.global_admin
        ///FROM
        ///(
        ///
        ///(SELECT 
        ///u.id,
        ///u.firstname,
        ///u.lastname,
        ///u.email,
        ///u.global_admin
        ///FROM user u
        ///WHERE (@search IS NULL 
        ///	OR LOWER(u.firstname) LIKE CONCAT(LOWER(@search), &apos;%&apos;)
        ///	OR LOWER(u.lastname) LIKE CONCAT(LOWER(@search), &apos;%&apos;)
        ///	OR LOWER(u.email) LIKE CONCAT(&apos;%&apos;, LOWER(@search), &apos;%&apos;))
        ///ORDER BY u.firstname, u.lastname, u.email
        ///LIMIT 0, @limit)
        ///
        ///UNION
        ///
        ///(SELECT 
        ///u.id,
        ///u.firstname,
        ///u.lastname,
        ///u.email,
        ///u.global_admin
        ///FROM  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectUsersByEmailFirstNameLastName {
            get {
                return ResourceManager.GetString("SelectUsersByEmailFirstNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT 
        ///u.id, 
        ///u.firstname,
        ///u.lastname,
        ///u.email,
        ///u.global_admin
        ///FROM user u
        ///JOIN group_user_mapping gum ON u.id = gum.user_id
        ///JOIN `group` g on g.id  = gum.group_id
        ///WHERE g.id = @groupId
        ///AND (@search IS NULL 
        ///	OR LOWER(u.firstname) LIKE CONCAT(LOWER(@search), &apos;%&apos;)
        ///	OR LOWER(u.lastname) LIKE CONCAT(LOWER(@search), &apos;%&apos;)
        ///	OR LOWER(u.email) LIKE CONCAT(&apos;%&apos;, LOWER(@search), &apos;%&apos;))
        ///ORDER BY u.email
        ///LIMIT @offset, @pageSize;.
        /// </summary>
        public static string SelectUsersByGroupId {
            get {
                return ResourceManager.GetString("SelectUsersByGroupId", resourceCulture);
            }
        }
    }
}
