//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.AggregateReport.Api.Dao {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AggregateReportApiDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal AggregateReportApiDaoResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.AggregateReport.Api.Dao.AggregateReportApiDaoResources", typeof(AggregateReportApiDaoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT sum(full_compliance_count) &apos;full_compliance_count&apos;,
        ///	sum(dkim_only_count) &apos;dkim_only_count&apos;,
        ///	sum(spf_only_count) &apos;spf_only_count&apos;
        ///FROM aggregate_daily_view adv
        ///WHERE effective_date BETWEEN @begin_date
        ///AND  @end_date
        ///AND (@domainId IS NULL OR domainId = @domainId);.
        /// </summary>
        public static string SelectComplianceAggregated {
            get {
                return ResourceManager.GetString("SelectComplianceAggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT effective_date &apos;date&apos;, sum(full_compliance_count) full_compliance_count, sum(dkim_only_count) &apos;dkim_only_count&apos;,sum(spf_only_count) &apos;spf_only_count&apos;
        ///FROM aggregate_daily_view adv
        ///WHERE effective_date BETWEEN @begin_date
        ///AND  @end_date
        ///AND (@domainId IS NULL OR domainId = @domainId) GROUP BY effective_date;.
        /// </summary>
        public static string SelectComplianceDaily {
            get {
                return ResourceManager.GetString("SelectComplianceDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT effective_date &apos;date&apos;, sum(disposition_none_count) &apos;disposition_none_count&apos;, sum(disposition_quarantine_count) &apos;disposition_quarantine_count&apos;,sum(disposition_reject_count) &apos;disposition_reject_count&apos;
        ///FROM aggregate_daily_view adv
        ///WHERE effective_date BETWEEN @begin_date
        ///AND  @end_date
        ///AND (@domainId IS NULL OR domainId = @domainId) GROUP BY effective_date;.
        /// </summary>
        public static string SelectDispositionDaily {
            get {
                return ResourceManager.GetString("SelectDispositionDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT id 
        ///FROM derived_domain
        ///WHERE id = @domainId;.
        /// </summary>
        public static string SelectDomain {
            get {
                return ResourceManager.GetString("SelectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT sum(disposition_none_count) &apos;disposition_none_count&apos;, sum(disposition_quarantine_count) &apos;disposition_quarantine_count&apos;, sum(disposition_reject_count) &apos;disposition_reject_count&apos;
        ///FROM aggregate_daily_view adv
        ///WHERE effective_date BETWEEN @begin_date
        ///AND  @end_date
        ///AND (@domainId IS NULL OR domainId = @domainId);.
        /// </summary>
        public static string SelectedDispositionAggregated {
            get {
                return ResourceManager.GetString("SelectedDispositionAggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  SELECT COUNT(DISTINCT domain) &apos;domain_count&apos;, SUM(aggregate_report_count) &apos;aggregate_report_count&apos;,sum(aggregate_report_record_count) &apos;aggregate_report_record_count&apos;, sum(total_email_count) &apos;total_email_count&apos;, sum(trusted_email_count) &apos;trusted_email_count&apos;, sum(untrusted_email_count) &apos;untrusted_email_count&apos;,sum(full_compliance_count) &apos;full_compliance_count&apos;,sum(dkim_only_count) &apos;dkim_only_count&apos;,sum(spf_only_count) &apos;spf_only_count&apos;, sum(disposition_none_count) &apos;disposition_none_count&apos;, sum(disposition_quar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectHeadlineAggregated {
            get {
                return ResourceManager.GetString("SelectHeadlineAggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  SELECT effective_date &apos;date&apos;, COUNT(DISTINCT domain) &apos;domain_count&apos;, sum(aggregate_report_count) &apos;aggregate_report_count&apos;,sum(aggregate_report_record_count) &apos;aggregate_report_record_count&apos;,sum(total_email_count) &apos;total_email_count&apos;, sum(trusted_email_count) &apos;trusted_email_count&apos;, sum(untrusted_email_count) &apos;untrusted_email_count&apos;,sum(full_compliance_count) &apos;full_compliance_count&apos;,sum(dkim_only_count) &apos;dkim_only_count&apos;,sum(spf_only_count) &apos;spf_only_count&apos;, sum(disposition_none_count) &apos;disposition_none_count&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectHeadlineDaily {
            get {
                return ResourceManager.GetString("SelectHeadlineDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT id,domain
        ///FROM derived_domain
        ///WHERE domain LIKE CONCAT(@domain_pattern,&apos;%&apos;)
        ///ORDER BY domain
        ///LIMIT 4;.
        /// </summary>
        public static string SelectMatchingDomains {
            get {
                return ResourceManager.GetString("SelectMatchingDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT  sum(trusted_email_count) &apos;trusted_email_count&apos;, sum(untrusted_email_count) &apos;untrusted_email_count&apos; FROM aggregate_daily_view adv
        ///WHERE effective_date BETWEEN @begin_date
        ///AND  @end_date
        ///AND (@domainId IS NULL OR domainId = @domainId);.
        /// </summary>
        public static string SelectTrustAggregated {
            get {
                return ResourceManager.GetString("SelectTrustAggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT effective_date &apos;date&apos;, sum(trusted_email_count) &apos;trusted_email_count&apos;, sum(untrusted_email_count) &apos;untrusted_email_count&apos; FROM aggregate_daily_view adv
        ///WHERE effective_date BETWEEN @begin_date
        ///AND  @end_date
        ///AND (@domainId IS NULL OR domainId = @domainId) GROUP BY effective_date;.
        /// </summary>
        public static string SelectTrustDaily {
            get {
                return ResourceManager.GetString("SelectTrustDaily", resourceCulture);
            }
        }
    }
}
