//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.AggregateReport.Api.Dao.Domain {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainsDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DomainsDaoResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.AggregateReport.Api.Dao.Domain.DomainsDaoResources", typeof(DomainsDaoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT id 
        ///FROM domain
        ///JOIN derived_aggregate_daily dad ON dad.domain_id = domain.id
        ///JOIN derived_user_domain_rollup_permissions dudrp 
        ///ON dad.domain_id = dudrp.domain_id
        ///WHERE dudrp.user_id = @userId 
        ///AND dudrp.domain_id = @domainId;.
        /// </summary>
        public static string SelectDomain {
            get {
                return ResourceManager.GetString("SelectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to (SELECT id,
        ///name 
        ///FROM domain 
        ///JOIN derived_user_domain_rollup_permissions dudrp 
        ///ON domain.id = dudrp.domain_id
        ///WHERE dudrp.user_id = @userId
        ///AND LOWER(domain.name) LIKE CONCAT(LOWER(@domain_pattern),&apos;%&apos;)
        ///ORDER BY name LIMIT 4)
        ///UNION
        ///(SELECT id,
        ///name 
        ///FROM domain 
        ///JOIN derived_user_domain_rollup_permissions dudrp 
        ///ON domain.id = dudrp.domain_id
        ///WHERE dudrp.user_id = @userId
        ///AND LOWER(domain.name) LIKE CONCAT(&apos;%&apos;,LOWER(@domain_pattern),&apos;%&apos;)
        ///ORDER BY name 
        ///LIMIT 4);.
        /// </summary>
        public static string SelectMatchingDomains {
            get {
                return ResourceManager.GetString("SelectMatchingDomains", resourceCulture);
            }
        }
    }
}
