//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.ForensicReport.Parser.Lambda.Dao.ForensicReport {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ForensicReportDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ForensicReportDaoResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.ForensicReport.Parser.Lambda.Dao.ForensicReport.ForensicReportDaoResources", typeof(ForensicReportDaoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  INSERT INTO `forensic_report` (
        ///`original_uri`, 
        ///`feedback_type`, 
        ///`user_agent`, 
        ///`version`, 
        ///`auth_failure`, 
        ///`original_envelope_id`, 
        ///`arrival_date`, 
        ///`reporting_mta`, 
        ///`source_ip_id`, 
        ///`incidents`, 
        ///`delivery_result`, 
        ///`message_id`,
        ///`provider_message_id`, 
        ///`dkim_domain`, 
        ///`dkim_identity`, 
        ///`dkim_selector`, 
        ///`dkim_canonicalized_header`, 
        ///`dkim_canonicalized_body`, 
        ///`spf_dns`, 
        ///`authentication_results`, 
        ///`reported_domain`, 
        ///`created_date`, 
        ///`request_id`) 
        ///VALUES (
        ///@original_uri, 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsertForensicReport {
            get {
                return ResourceManager.GetString("InsertForensicReport", resourceCulture);
            }
        }
    }
}
