using System.Collections.Generic;
using System.Linq;
using Dmarc.Common.Interface.Logging;
using MimeKit;

namespace Dmarc.AggregateReport.Parser.Lambda.Parser
{
    public interface IContentTypeProvider
    {
        string GetContentType(MimePart mimePart);
    }

    public class ContentTypeProvider : IContentTypeProvider
    {
        private const string AlternativeContentTypeHeader = "ContentType";

        private readonly ILogger _log;

        public ContentTypeProvider(ILogger log)
        {
            _log = log;
        }

        //This handles case where ContentType is used instead of Content-Type
        //this is seen in aggregate reports generated by Trustwave SEG software.
        public string GetContentType(MimePart mimePart)
        {
            string contentType = mimePart.ContentType.MimeType.ToLower();

            if (contentType == ContentType.TextPlain)
            {
                Dictionary<string, Header> headers = mimePart.Headers.ToDictionary(_ => _.Field);

                Header header;

                if (headers.TryGetValue(AlternativeContentTypeHeader, out header))
                {
                    MimeKit.ContentType updatedContentType = MimeKit.ContentType.Parse(ParserOptions.Default, header.RawValue);

                    string updatedContentTypeString = updatedContentType.MimeType.ToLower();
                    _log.Info($"Updated content type from {contentType} to {updatedContentTypeString}");
                    return updatedContentTypeString;
                }
            }

            return contentType;
        }
    }
}