//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.AggregateReport.Api.Dao.Sender {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SenderStatisticsDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal SenderStatisticsDaoResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.AggregateReport.Api.Dao.Sender.SenderStatisticsDaoResources", typeof(SenderStatisticsDaoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  SELECT top10.source_ip, 
        ///SUM(`full_compliance_count`) `full_compliance_count`, 
        ///SUM(`dkim_only_count`) `dkim_only_count`, 
        ///SUM(`spf_only_count`) `spf_only_count`,
        ///SUM(`untrusted_email_count`) `untrusted_email_count`,
        ///SUM(`trusted_email_count`) `trusted_email_count`,
        ///SUM(`disposition_quarantine_count`) `disposition_quarantine_count`,
        ///SUM(`disposition_reject_count`) `disposition_reject_count`,
        ///SUM(`disposition_none_count`) `disposition_none_count`,
        ///SUM(`total_email_count`) `total_email_count`,
        ///SUM(` [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectTopDkimNoSpfSenders {
            get {
                return ResourceManager.GetString("SelectTopDkimNoSpfSenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  SELECT top10.source_ip, 
        ///SUM(`full_compliance_count`) `full_compliance_count`, 
        ///SUM(`dkim_only_count`) `dkim_only_count`, 
        ///SUM(`spf_only_count`) `spf_only_count`,
        ///SUM(`untrusted_email_count`) `untrusted_email_count`,
        ///SUM(`trusted_email_count`) `trusted_email_count`,
        ///SUM(`disposition_quarantine_count`) `disposition_quarantine_count`,
        ///SUM(`disposition_reject_count`) `disposition_reject_count`,
        ///SUM(`disposition_none_count`) `disposition_none_count`,
        ///SUM(`total_email_count`) `total_email_count`,
        ///SUM(` [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectTopSpfNoDkimSenders {
            get {
                return ResourceManager.GetString("SelectTopSpfNoDkimSenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  SELECT top10.source_ip, 
        ///SUM(`full_compliance_count`) `full_compliance_count`, 
        ///SUM(`dkim_only_count`) `dkim_only_count`, 
        ///SUM(`spf_only_count`) `spf_only_count`,
        ///SUM(`untrusted_email_count`) `untrusted_email_count`,
        ///SUM(`trusted_email_count`) `trusted_email_count`,
        ///SUM(`disposition_quarantine_count`) `disposition_quarantine_count`,
        ///SUM(`disposition_reject_count`) `disposition_reject_count`,
        ///SUM(`disposition_none_count`) `disposition_none_count`,
        ///SUM(`total_email_count`) `total_email_count`,
        ///SUM(` [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectTopTrustedSenders {
            get {
                return ResourceManager.GetString("SelectTopTrustedSenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  SELECT top10.source_ip, 
        ///SUM(`full_compliance_count`) `full_compliance_count`, 
        ///SUM(`dkim_only_count`) `dkim_only_count`, 
        ///SUM(`spf_only_count`) `spf_only_count`,
        ///SUM(`untrusted_email_count`) `untrusted_email_count`,
        ///SUM(`trusted_email_count`) `trusted_email_count`,
        ///SUM(`disposition_quarantine_count`) `disposition_quarantine_count`,
        ///SUM(`disposition_reject_count`) `disposition_reject_count`,
        ///SUM(`disposition_none_count`) `disposition_none_count`,
        ///SUM(`total_email_count`) `total_email_count`,
        ///SUM(` [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectTopUntrustedSenders {
            get {
                return ResourceManager.GetString("SelectTopUntrustedSenders", resourceCulture);
            }
        }
    }
}
