module "processor-cluster" {
  source                    = "../../modules/ECScluster-module"
  cluster-name              = "processor"
  vpc-id                    = "${aws_vpc.dmarc-env.id}"
  ssh-key-name              = "${var.ssh-key-name}"
  availability-zones        = "${join(",", values(var.zone-names))}"
  subnet-ids                = "${join(",", aws_subnet.dmarc-env-subnet.*.id)}"
  subnet-cidr               = "${join(",", values(var.zone-subnets))}"
  container-memory          = "${var.default-container-memory}"
  rds-sg-id                 = "${aws_security_group.rds.id}"
  db-access                 = "true"
  sqs-access                = "true"
  sns-access                = "true"
  default-instance-type     = "t2.small"
  default-instance-count    = "1"
  prod-stage-instance-type  = "t2.medium"
  prod-stage-instance-count = "3"
  health-check-grace-period = "300"
  parameter-store-access    = "true"

  // route53-zone-id                    = "${aws_route53_zone.service-zone.id}"
  aws-region                         = "${var.aws-region}"
  env-name                           = "${var.env-name}"
  aws-account-id                     = "${var.aws-account-id}"
  admin-subnets                      = "${var.build-vpc == "" ? "" : var.build-vpc-cidr-block}"
  cloudwatch-alerts-sns-arn          = "${aws_sns_topic.cloudwatch-alerts.arn}"
  egress-internet-custom-ports       = "25,2525,587,465"
  egress-internet-custom-ports-count = "4"
}
