module "loadbalancer-external" {
  source                    = "../../modules/loadBalancer-module"
  balancer-name             = "frontend"
  balancer-fqdn             = "${var.web-url}"
  certificate-name          = "${var.web-url}"
  vpc-id                    = "${aws_vpc.dmarc-env.id}"
  lb-subnet-ids             = "${join(",", aws_subnet.dmarc-env-public-subnet.*.id)}"
  instance-subnet-cidr      = "${join(",", values(var.frontend-zone-subnets))}"
  lb-internal               = "false"
  lb-ingress-subnets1       = "${var.env-name == "prod" && var.disable-firewall == "true" ? "0.0.0.0/0" : module.sourceip.internal-sources-acl }"
  lb-ingress-subnets2       = "${var.env-name == "staging"  ? module.sourceip.external-sources-acl : "" }"
  lb-target-count           = "1"
  lb-target-paths           = "root"
  health-check-grace-period = "300"
  http-listener             = "true"
  aws-region                = "${var.aws-region}"
  env-name                  = "${var.env-name}"
  aws-account-id            = "${var.aws-account-id}"
  admin-subnets             = "${var.build-vpc == "" ? "" : var.build-vpc-cidr-block}"
  route53-zone-id           = "${data.aws_route53_zone.dmarc-zone.zone_id}"
  cloudwatch-alerts-sns-arn = "${aws_sns_topic.cloudwatch-alerts.arn}"
  healthcheck-path          = "/healthcheck/"
}
