//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.Admin.Api.Dao.Domain {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DomainDaoResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.Admin.Api.Dao.Domain.DomainDaoResources", typeof(DomainDaoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to INSERT INTO domain
        ///(name,publish, created_by)
        ///VALUES
        ///(@name,b&apos;1&apos;, @createdBy) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id), publish=b&apos;1&apos;;.
        /// </summary>
        public static string InsertDomain {
            get {
                return ResourceManager.GetString("InsertDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT id, name 
        ///FROM domain
        ///WHERE id = @id and publish=b&apos;1&apos;;.
        /// </summary>
        public static string SelectDomainById {
            get {
                return ResourceManager.GetString("SelectDomainById", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT d.id, d.name
        ///FROM domain d
        ///JOIN group_domain_mapping gdm ON d.id = gdm.domain_id
        ///JOIN `group` g ON g.id = gdm.group_id
        ///WHERE d.publish = b&apos;1&apos; 
        ///AND g.id = @groupId
        ///AND (@search IS NULL OR LOWER(d.name) LIKE CONCAT(LOWER(@search), &apos;%&apos;))
        ///ORDER BY d.name
        ///LIMIT @offset, @pageSize;.
        /// </summary>
        public static string SelectDomainsByGroupId {
            get {
                return ResourceManager.GetString("SelectDomainsByGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT 
        ///d1.id,
        ///d1.name
        ///FROM
        ///(
        ///
        ///(SELECT 
        ///d.id,
        ///d.name
        ///FROM domain d
        ///WHERE d.publish=b&apos;1&apos; AND  (@search IS NULL OR LOWER(d.name) LIKE CONCAT(&apos;%&apos;, LOWER(@search), &apos;%&apos;))
        ///ORDER BY d.name
        ///LIMIT 0, @limit)
        ///
        ///UNION
        ///
        ///(SELECT 
        ///d.id,
        ///d.name
        ///FROM domain d
        ///WHERE d.publish=b&apos;1&apos; AND d.id IN ({0}))
        ///) d1
        ///ORDER by d1.name.
        /// </summary>
        public static string SelectDomainsByName {
            get {
                return ResourceManager.GetString("SelectDomainsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT d.id, d.name
        ///FROM domain d
        ///JOIN group_domain_mapping gdm ON d.id = gdm.domain_id
        ///JOIN `group` g ON g.id = gdm.group_id
        ///JOIN group_user_mapping gum ON g.id = gum.group_id
        ///JOIN user u on u.id = gum.user_id
        ///WHERE d.publish=b&apos;1&apos; AND u.id = @userId
        ///AND (@search IS NULL OR LOWER(d.name) LIKE CONCAT(LOWER(@search), &apos;%&apos;))
        ///ORDER BY d.name
        ///LIMIT @offset, @pageSize;.
        /// </summary>
        public static string SelectDomainsByUserId {
            get {
                return ResourceManager.GetString("SelectDomainsByUserId", resourceCulture);
            }
        }
    }
}
