//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.Lambda.AggregateReport.Parser.Test.Serialisation.AggregateReportDeserialisation {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DkimAuthResultSerialiserTestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DkimAuthResultSerialiserTestsResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.AggregateReport.Parser.Lambda.Test.Serialisation.AggregateReportDeserialisa" +
                            "tion.DkimAuthResultSerialiserTestsResources", typeof(DkimAuthResultSerialiserTestsResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;dkim&gt;
        ///	&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///	&lt;result&gt;asdfasd&lt;/result&gt;
        ///	&lt;human_result&gt;humanresult&lt;/human_result&gt;
        ///&lt;/dkim&gt;.
        /// </summary>
        public static string InvalidResultValue {
            get {
                return ResourceManager.GetString("InvalidResultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;dkim&gt;
        ///	&lt;result&gt;neutral&lt;/result&gt;
        ///	&lt;human_result&gt;humanresult&lt;/human_result&gt;
        ///&lt;/dkim&gt;.
        /// </summary>
        public static string NoDomainTag {
            get {
                return ResourceManager.GetString("NoDomainTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;dkim&gt;
        ///	&lt;domain&gt;&lt;/domain&gt;
        ///	&lt;result&gt;neutral&lt;/result&gt;
        ///	&lt;human_result&gt;humanresult&lt;/human_result&gt;
        ///&lt;/dkim&gt;.
        /// </summary>
        public static string NoDomainValue {
            get {
                return ResourceManager.GetString("NoDomainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;dkim&gt;
        ///	&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///	&lt;result&gt;neutral&lt;/result&gt;
        ///&lt;/dkim&gt;.
        /// </summary>
        public static string NoHumanResultTag {
            get {
                return ResourceManager.GetString("NoHumanResultTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;dkim&gt;
        ///	&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///	&lt;result&gt;neutral&lt;/result&gt;
        ///	&lt;human_result&gt;&lt;/human_result&gt;
        ///&lt;/dkim&gt;.
        /// </summary>
        public static string NoHumanResultValue {
            get {
                return ResourceManager.GetString("NoHumanResultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;dkim&gt;
        ///	&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///	&lt;human_result&gt;humanresult&lt;/human_result&gt;
        ///&lt;/dkim&gt;.
        /// </summary>
        public static string NoResultTag {
            get {
                return ResourceManager.GetString("NoResultTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;dkim&gt;
        ///	&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///	&lt;result&gt;&lt;/result&gt;
        ///	&lt;human_result&gt;humanresult&lt;/human_result&gt;
        ///&lt;/dkim&gt;.
        /// </summary>
        public static string NoResultValue {
            get {
                return ResourceManager.GetString("NoResultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;dkim&gt;
        ///	&lt;not_dkim&gt;
        ///		&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///		&lt;result&gt;&lt;/result&gt;
        ///		&lt;human_result&gt;humanresult&lt;/human_result&gt;
        ///	&lt;/not_dkim&gt;
        ///&lt;/dkim&gt;.
        /// </summary>
        public static string NotDirectDescendants {
            get {
                return ResourceManager.GetString("NotDirectDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;not_dkim&gt;
        ///	&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///	&lt;result&gt;&lt;/result&gt;
        ///	&lt;human_result&gt;humanresult&lt;/human_result&gt;
        ///&lt;/not_dkim&gt;.
        /// </summary>
        public static string NotDkim {
            get {
                return ResourceManager.GetString("NotDkim", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;dkim&gt;
        ///	&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///	&lt;result&gt;neutral&lt;/result&gt;
        ///	&lt;human_result&gt;humanresult&lt;/human_result&gt;
        ///&lt;/dkim&gt;.
        /// </summary>
        public static string StandardDkimAuthResult {
            get {
                return ResourceManager.GetString("StandardDkimAuthResult", resourceCulture);
            }
        }
    }
}
