//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.Lambda.AggregateReport.Parser.Test.Serialisation.AggregateReportDeserialisation {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PolicyPublishedDeserialiserTestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal PolicyPublishedDeserialiserTestsResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.AggregateReport.Parser.Lambda.Test.Serialisation.AggregateReportDeserialisa" +
                            "tion.PolicyPublishedDeserialiserTestsResources", typeof(PolicyPublishedDeserialiserTestsResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;d&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string InvalidAdkim {
            get {
                return ResourceManager.GetString("InvalidAdkim", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;d&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string InvalidAspf {
            get {
                return ResourceManager.GetString("InvalidAspf", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;asdf&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string InvalidP {
            get {
                return ResourceManager.GetString("InvalidP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;asdf&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string InvalidPct {
            get {
                return ResourceManager.GetString("InvalidPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;asdf&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string InvalidSp {
            get {
                return ResourceManager.GetString("InvalidSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        ///&lt;/policy_published&gt;.
        /// </summary>
        public static string MultipleAspf {
            get {
                return ResourceManager.GetString("MultipleAspf", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        ///&lt;/policy_published&gt;.
        /// </summary>
        public static string MultipleDomain {
            get {
                return ResourceManager.GetString("MultipleDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        ///&lt;/policy_published&gt;.
        /// </summary>
        public static string MultipleP {
            get {
                return ResourceManager.GetString("MultipleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        ///&lt;/policy_published&gt;.
        /// </summary>
        public static string MultiplePct {
            get {
                return ResourceManager.GetString("MultiplePct", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        ///&lt;/policy_published&gt;.
        /// </summary>
        public static string MultipleSp {
            get {
                return ResourceManager.GetString("MultipleSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        ///&lt;/policy_published&gt;.
        /// </summary>
        public static string MutlipleAdkim {
            get {
                return ResourceManager.GetString("MutlipleAdkim", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string NoAdkim {
            get {
                return ResourceManager.GetString("NoAdkim", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string NoAspf {
            get {
                return ResourceManager.GetString("NoAspf", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string NoDomain {
            get {
                return ResourceManager.GetString("NoDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string NoP {
            get {
                return ResourceManager.GetString("NoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string NoPct {
            get {
                return ResourceManager.GetString("NoPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;feedback&gt;
        ///    &lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///    &lt;adkim&gt;r&lt;/adkim&gt;
        ///    &lt;aspf&gt;r&lt;/aspf&gt;
        ///    &lt;p&gt;none&lt;/p&gt;
        ///    &lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/feedback&gt;.
        /// </summary>
        public static string NoPolicyPublished {
            get {
                return ResourceManager.GetString("NoPolicyPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gsi.gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string NoSp {
            get {
                return ResourceManager.GetString("NoSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;not_policy_published&gt;
        ///		&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///		&lt;adkim&gt;r&lt;/adkim&gt;
        ///		&lt;aspf&gt;r&lt;/aspf&gt;
        ///		&lt;p&gt;none&lt;/p&gt;
        ///		&lt;sp&gt;none&lt;/sp&gt;
        ///		&lt;pct&gt;100&lt;/pct&gt;
        ///	&lt;/not_policy_published&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string NotDirectDescendants {
            get {
                return ResourceManager.GetString("NotDirectDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;policy_published&gt;
        ///	&lt;domain&gt;gov.uk&lt;/domain&gt;
        ///	&lt;adkim&gt;r&lt;/adkim&gt;
        ///	&lt;aspf&gt;r&lt;/aspf&gt;
        ///	&lt;p&gt;none&lt;/p&gt;
        ///	&lt;sp&gt;none&lt;/sp&gt;
        ///	&lt;pct&gt;100&lt;/pct&gt;
        /// &lt;/policy_published&gt;.
        /// </summary>
        public static string PolicyPublishedStandard {
            get {
                return ResourceManager.GetString("PolicyPublishedStandard", resourceCulture);
            }
        }
    }
}
