//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.Lambda.AggregateReport.Parser.Test.Serialisation.AggregateReportDeserialisation {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportMetadataParserTestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ReportMetadataParserTestsResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.AggregateReport.Parser.Lambda.Test.Serialisation.AggregateReportDeserialisa" +
                            "tion.ReportMetadataParserTestsResources", typeof(ReportMetadataParserTestsResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;asdf&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string BeginNotInt {
            get {
                return ResourceManager.GetString("BeginNotInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;asdfas&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string EndNotInt {
            get {
                return ResourceManager.GetString("EndNotInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string MultipleBegin {
            get {
                return ResourceManager.GetString("MultipleBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string MultipleDateRange {
            get {
                return ResourceManager.GetString("MultipleDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string MultipleEmail {
            get {
                return ResourceManager.GetString("MultipleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string MultipleEnd {
            get {
                return ResourceManager.GetString("MultipleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        ///	&lt;error&gt;badness2&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string MultipleError {
            get {
                return ResourceManager.GetString("MultipleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo2@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string MultipleExtraContactInfo {
            get {
                return ResourceManager.GetString("MultipleExtraContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string MultipleOrgName {
            get {
                return ResourceManager.GetString("MultipleOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string MultipleReportId {
            get {
                return ResourceManager.GetString("MultipleReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string NoBegin {
            get {
                return ResourceManager.GetString("NoBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string NoDateRange {
            get {
                return ResourceManager.GetString("NoDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string NoEmail {
            get {
                return ResourceManager.GetString("NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string NoEnd {
            get {
                return ResourceManager.GetString("NoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string NoExtraContactInfo {
            get {
                return ResourceManager.GetString("NoExtraContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string NoOrgName {
            get {
                return ResourceManager.GetString("NoOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string NoReportId {
            get {
                return ResourceManager.GetString("NoReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;feedback&gt;
        ///    &lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        ///&lt;/feedback&gt;.
        /// </summary>
        public static string NoReportMetadata {
            get {
                return ResourceManager.GetString("NoReportMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;not_report_metadata&gt;
        ///		&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///		&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///		&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///		&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///		&lt;date_range&gt;
        ///			&lt;begin&gt;1476403200&lt;/begin&gt;
        ///			&lt;end&gt;1476489599&lt;/end&gt;
        ///		&lt;/date_range&gt;
        ///		&lt;error&gt;badness&lt;/error&gt;
        ///	&lt;/not_report_metadata&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string NotDirectDescendants {
            get {
                return ResourceManager.GetString("NotDirectDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;report_metadata&gt;
        ///	&lt;org_name&gt;Provider&lt;/org_name&gt;
        ///	&lt;email&gt;dmarc@provider.com&lt;/email&gt;
        ///	&lt;extra_contact_info&gt;dmarcinfo@provider.com&lt;/extra_contact_info&gt;
        ///	&lt;report_id&gt;14764962785345167802&lt;/report_id&gt;
        ///	&lt;date_range&gt;
        ///		&lt;begin&gt;1476403200&lt;/begin&gt;
        ///		&lt;end&gt;1476489599&lt;/end&gt;
        ///	&lt;/date_range&gt;
        ///	&lt;error&gt;badness&lt;/error&gt;
        /// &lt;/report_metadata&gt;.
        /// </summary>
        public static string StandardReportMetadata {
            get {
                return ResourceManager.GetString("StandardReportMetadata", resourceCulture);
            }
        }
    }
}
