//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.Lambda.AggregateReport.Parser.Test.Serialisation.AggregateReportDeserialisation {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RowDeserialiserTestsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal RowDeserialiserTestsResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.AggregateReport.Parser.Lambda.Test.Serialisation.AggregateReportDeserialisa" +
                            "tion.RowDeserialiserTestsResource", typeof(RowDeserialiserTestsResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;row&gt;
        ///  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///  &lt;count&gt;40&lt;/count&gt;
        ///  &lt;count&gt;40&lt;/count&gt;
        ///  &lt;policy_evaluated&gt;
        ///  &lt;/policy_evaluated&gt;
        ///&lt;/row&gt;.
        /// </summary>
        public static string DuplicateCountTags {
            get {
                return ResourceManager.GetString("DuplicateCountTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;row&gt;
        ///  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///  &lt;count&gt;40&lt;/count&gt;
        ///  &lt;policy_evaluated&gt;
        ///  &lt;/policy_evaluated&gt;
        ///&lt;/row&gt;.
        /// </summary>
        public static string DuplicateIpTags {
            get {
                return ResourceManager.GetString("DuplicateIpTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;row&gt;
        ///  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///  &lt;count&gt;40&lt;/count&gt;
        ///  &lt;policy_evaluated&gt;
        ///  &lt;/policy_evaluated&gt;
        ///  &lt;policy_evaluated&gt;
        ///  &lt;/policy_evaluated&gt;
        ///&lt;/row&gt;.
        /// </summary>
        public static string DuplicatePolicyEvaluatedTags {
            get {
                return ResourceManager.GetString("DuplicatePolicyEvaluatedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;row&gt;
        ///  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///  &lt;count&gt;asdf&lt;/count&gt;
        ///  &lt;policy_evaluated&gt;
        ///  &lt;/policy_evaluated&gt;
        ///&lt;/row&gt;.
        /// </summary>
        public static string InvalidCount {
            get {
                return ResourceManager.GetString("InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;row&gt;
        ///  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///  &lt;policy_evaluated&gt;
        ///  &lt;/policy_evaluated&gt;
        ///&lt;/row&gt;.
        /// </summary>
        public static string NoCount {
            get {
                return ResourceManager.GetString("NoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;row&gt;
        ///  &lt;count&gt;40&lt;/count&gt;
        ///  &lt;policy_evaluated&gt;
        ///  &lt;/policy_evaluated&gt;
        ///&lt;/row&gt;.
        /// </summary>
        public static string NoIpTag {
            get {
                return ResourceManager.GetString("NoIpTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;row&gt;
        ///  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///  &lt;count&gt;40&lt;/count&gt;
        ///&lt;/row&gt;.
        /// </summary>
        public static string NoPolicyEvaluated {
            get {
                return ResourceManager.GetString("NoPolicyEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;row&gt;
        ///	&lt;not_row&gt;
        ///	  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///	  &lt;count&gt;40&lt;/count&gt;
        ///	  &lt;policy_evaluated&gt;
        ///	  &lt;/policy_evaluated&gt;
        ///  &lt;/not_row&gt;
        ///&lt;/row&gt;.
        /// </summary>
        public static string NotDirectDescendants {
            get {
                return ResourceManager.GetString("NotDirectDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;not_row&gt;
        ///  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///  &lt;count&gt;40&lt;/count&gt;
        ///  &lt;policy_evaluated&gt;
        ///  &lt;/policy_evaluated&gt;
        ///&lt;/not_row&gt;.
        /// </summary>
        public static string NotRow {
            get {
                return ResourceManager.GetString("NotRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;row&gt;
        ///  &lt;source_ip&gt;192.168.1.1&lt;/source_ip&gt;
        ///  &lt;count&gt;40&lt;/count&gt;
        ///  &lt;policy_evaluated&gt;
        ///  &lt;/policy_evaluated&gt;
        ///&lt;/row&gt;.
        /// </summary>
        public static string StandardRow {
            get {
                return ResourceManager.GetString("StandardRow", resourceCulture);
            }
        }
    }
}
