//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.DnsRecord.Evaluator.Dmarc.Explainers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DmarcExplainerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DmarcExplainerResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.DnsRecord.Evaluator.Dmarc.Explainers.DmarcExplainerResource", typeof(DmarcExplainerResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to DKIM domain field must match any sub domain of the domain in From: email header..
        /// </summary>
        public static string AdkimRelaxedExplanation {
            get {
                return ResourceManager.GetString("AdkimRelaxedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to DKIM domain field must match exactly the domain in From: email header..
        /// </summary>
        public static string AdkimStrictExplanation {
            get {
                return ResourceManager.GetString("AdkimStrictExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SPF domain field must match any sub domain of the domain in  SMTP HELO / SMTP MAIL FROM..
        /// </summary>
        public static string AspfRelaxedExplanation {
            get {
                return ResourceManager.GetString("AspfRelaxedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SPF domain field must match exactly the domain in  SMTP HELO / SMTP MAIL FROM..
        /// </summary>
        public static string AspfStrictExplanation {
            get {
                return ResourceManager.GetString("AspfStrictExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generate a forensic report if DKIM check fails..
        /// </summary>
        public static string FailureOptionsDExplanation {
            get {
                return ResourceManager.GetString("FailureOptionsDExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generate a forensic report if SPF or DKIM checks fail..
        /// </summary>
        public static string FailureOptionsOneExplanation {
            get {
                return ResourceManager.GetString("FailureOptionsOneExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generate a forensic report if SPF check fails..
        /// </summary>
        public static string FailureOptionsSExplanation {
            get {
                return ResourceManager.GetString("FailureOptionsSExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generate a forensic report if SPF and DKIM checks fail..
        /// </summary>
        public static string FailureOptionsZeroExplanation {
            get {
                return ResourceManager.GetString("FailureOptionsZeroExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Policy (p) applies to {0} % of unauthorised mail for this domain..
        /// </summary>
        public static string PercentExplanation {
            get {
                return ResourceManager.GetString("PercentExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mail servers receiving mail for this domain will report statistics for messages from this domain..
        /// </summary>
        public static string PolicyNoneExplanation {
            get {
                return ResourceManager.GetString("PolicyNoneExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mail servers receiving mail for this domain will report statistics for messages from this domain and will mark as messages as spam (usually ending up in recipients spam folder)..
        /// </summary>
        public static string PolicyQuarantineExplanation {
            get {
                return ResourceManager.GetString("PolicyQuarantineExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mail servers receiving mail for this domain will report statistics for messages from this domain and will reject messages as spam (message wont reach recipient)..
        /// </summary>
        public static string PolicyRejectExplanation {
            get {
                return ResourceManager.GetString("PolicyRejectExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Forensic reports will be sent in AFRF (Authentication Failure Reporting Format) format..
        /// </summary>
        public static string ReportFormatAFRFExplanation {
            get {
                return ResourceManager.GetString("ReportFormatAFRFExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aggregate reports should be sent every {0} seconds ({1} hours)..
        /// </summary>
        public static string ReportIntervalExplanation {
            get {
                return ResourceManager.GetString("ReportIntervalExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Send aggregate reports to: {0}..
        /// </summary>
        public static string ReportUriAggregateExplanation {
            get {
                return ResourceManager.GetString("ReportUriAggregateExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Send forensic reports to: {0}..
        /// </summary>
        public static string ReportUriForensicExplanation {
            get {
                return ResourceManager.GetString("ReportUriForensicExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mail servers receiving mail for subdomains of this domain will report statistics for messages from subdomains..
        /// </summary>
        public static string SubDomainPolicyNoneExplanation {
            get {
                return ResourceManager.GetString("SubDomainPolicyNoneExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mail servers receiving mail for subdomains of this domain will report statistics for messages from subdomains and will mark as messages as spam (usually ending up in recipients spam folder)..
        /// </summary>
        public static string SubDomainPolicyQuarantineExplanation {
            get {
                return ResourceManager.GetString("SubDomainPolicyQuarantineExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mail servers receiving mail for subdomains of this domain will report statistics for messages from subdomains and will reject messages as spam (message wont reach recipient)..
        /// </summary>
        public static string SubDomainPolicyRejectExplanation {
            get {
                return ResourceManager.GetString("SubDomainPolicyRejectExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to DMARC version 1..
        /// </summary>
        public static string VersionDmarc1Explanation {
            get {
                return ResourceManager.GetString("VersionDmarc1Explanation", resourceCulture);
            }
        }
    }
}
