//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.MxSecurityEvaluator.Dao {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TlsRecordDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal TlsRecordDaoResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.MxSecurityEvaluator.Dao.TlsRecordDaoResources", typeof(TlsRecordDaoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SELECT drm.hostname, drmtp.* FROM domain d
        ///JOIN dns_record_mx drm 
        ///ON d.id = drm.domain_id 
        ///JOIN dns_record_mx_tls_profile_results drmtp 
        ///ON drm.id = drmtp.mx_record_id 
        ///WHERE d.id = @domain_id
        ///AND drmtp.end_date IS NULL;.
        /// </summary>
        public static string GetDomainTlsConnectionResults {
            get {
                return ResourceManager.GetString("GetDomainTlsConnectionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to INSERT INTO dns_record_mx_tls_evaluator_results 
        ///SET mx_record_id = @mx_record_id,
        ///last_checked = @last_checked,
        ///data = @data
        ///ON DUPLICATE KEY UPDATE
        ///last_checked = @last_checked,
        ///data = @data;.
        /// </summary>
        public static string InsertTlsEvaluatorResults {
            get {
                return ResourceManager.GetString("InsertTlsEvaluatorResults", resourceCulture);
            }
        }
    }
}
