SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `derived_weekly_stats_forensic`;
DROP TABLE IF EXISTS `forensic_binary`;
DROP TABLE IF EXISTS `forensic_binary_hash`;
DROP TABLE IF EXISTS `forensic_binary_match`;
DROP TABLE IF EXISTS `forensic_binary_report`;
DROP TABLE IF EXISTS `forensic_report`;
DROP TABLE IF EXISTS `forensic_report_mail_from`;
DROP TABLE IF EXISTS `forensic_report_rcpt_to`;
DROP TABLE IF EXISTS `forensic_reported_uri`;
DROP TABLE IF EXISTS `forensic_text`;
DROP TABLE IF EXISTS `forensic_text_hash`;
DROP TABLE IF EXISTS `forensic_text_match`;
DROP TABLE IF EXISTS `forensic_uri`;
DROP TABLE IF EXISTS `forensic_uri_match`;
DROP TABLE IF EXISTS `forensic_uri_report`;
DROP TABLE IF EXISTS `ip_org`;
DROP TABLE IF EXISTS `ip_subnet`;
DROP TABLE IF EXISTS `hostname`;
DROP TABLE IF EXISTS `rfc822_header_fields`;
DROP TABLE IF EXISTS `rfc822_header_mapping`;
DROP TABLE IF EXISTS `rfc822_header_set`;
DROP TABLE IF EXISTS `rfc822_header_text_values`;
DROP TABLE IF EXISTS `content_type`;
DROP TABLE IF EXISTS `derived_aggregate_daily_old`;
DROP TABLE IF EXISTS `derived_aggregate_daily_rollup_old`;
DROP TABLE IF EXISTS `derived_aggregate_daily_senders_top10_old`;
DROP TABLE IF EXISTS `derived_aggregate_daily_senders_top10_dkim_only_count`;
DROP TABLE IF EXISTS `derived_aggregate_daily_senders_top10_full_compliance_count`;
DROP TABLE IF EXISTS `derived_aggregate_daily_senders_top10_untrusted_email_count`;
DROP TABLE IF EXISTS `derived_aggregate_daily_senders_top10_spf_only_count`;
DROP TABLE IF EXISTS `derived_aggregate_daily_senders_top10_rollup_old`;
DROP TABLE IF EXISTS `derived_aggregate_top10_daily_threshold_old`;
DROP TABLE IF EXISTS `derived_job_semaphore_old`;
DROP TABLE IF EXISTS `derived_policy_history`;
DROP TABLE IF EXISTS `email_address`;

SET foreign_key_checks = 1;
