//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.DnsRecord.Evaluator.Spf.Explainers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpfExplainerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal SpfExplainerResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.DnsRecord.Evaluator.Spf.Explainers.SpfExplainerResource", typeof(SpfExplainerResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} ip addresses mentioned in A or AAAA record for {1} with ipv4 cidr block {2} and ipv6 cidr block {3}..
        /// </summary>
        public static string AExplanation {
            get {
                return ResourceManager.GetString("AExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} any (other) ip addresses..
        /// </summary>
        public static string AllExplanation {
            get {
                return ResourceManager.GetString("AllExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} if A record query for {1} succeeds. Result of query is irrelevant..
        /// </summary>
        public static string ExistsExplanation {
            get {
                return ResourceManager.GetString("ExistsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Use {0} to generate explanation for failure..
        /// </summary>
        public static string ExplanationExplanation {
            get {
                return ResourceManager.GetString("ExplanationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}  ip addresses mentioned in SPF record for {1}..
        /// </summary>
        public static string IncludeExplanation {
            get {
                return ResourceManager.GetString("IncludeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} ip address {1} with cidr block {2}..
        /// </summary>
        public static string IpExplanation {
            get {
                return ResourceManager.GetString("IpExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} ip addresses mentioned in MX record for {1} with ipv4 cidr block {2} and ipv6 cidr block {3}..
        /// </summary>
        public static string MxExplanation {
            get {
                return ResourceManager.GetString("MxExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Do not allow.
        /// </summary>
        public static string QualifierFailExplanation {
            get {
                return ResourceManager.GetString("QualifierFailExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Allow without evaluation.
        /// </summary>
        public static string QualifierNeutralExplanation {
            get {
                return ResourceManager.GetString("QualifierNeutralExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Allow.
        /// </summary>
        public static string QualifierPassExplanation {
            get {
                return ResourceManager.GetString("QualifierPassExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Allow but mark.
        /// </summary>
        public static string QualifierSoftFailExplanation {
            get {
                return ResourceManager.GetString("QualifierSoftFailExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} is not a recognised modifier..
        /// </summary>
        public static string UnknownModifierExplanation {
            get {
                return ResourceManager.GetString("UnknownModifierExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} is not a recognised term..
        /// </summary>
        public static string UnknownTermExplanation {
            get {
                return ResourceManager.GetString("UnknownTermExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SPF version 1..
        /// </summary>
        public static string VersionExplanation {
            get {
                return ResourceManager.GetString("VersionExplanation", resourceCulture);
            }
        }
    }
}
