//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmarc.MxSecurityTester.Dao {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TlsSecurityProfileDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal TlsSecurityProfileDaoResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmarc.MxSecurityTester.Dao.TlsSecurityProfileDaoResources", typeof(TlsSecurityProfileDaoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to INSERT INTO `certificate`
        ///(`thumb_print`,
        ///`issuer`,
        ///`subject`,
        ///`start_date`,
        ///`end_date`,
        ///`key_length`,
        ///`algorithm`,
        ///`serial_number`,
        ///`version`,
        ///`valid`)
        ///VALUES.
        /// </summary>
        public static string InsertCertificates {
            get {
                return ResourceManager.GetString("InsertCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ON DUPLICATE KEY UPDATE `thumb_print` = VALUES(`thumb_print`);.
        /// </summary>
        public static string InsertCertificatesOnDuplicateKey {
            get {
                return ResourceManager.GetString("InsertCertificatesOnDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to (@a{0},
        ///@b{0},
        ///@c{0},
        ///@d{0},
        ///@e{0},
        ///@f{0},
        ///@g{0},
        ///@h{0},
        ///@i{0},
        ///@j{0}).
        /// </summary>
        public static string InsertCertificateValuesFormatString {
            get {
                return ResourceManager.GetString("InsertCertificateValuesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to INSERT INTO `certificate_mapping`
        ///(`sequence`,
        ///`dns_record_mx_tls_profile_2_id`,
        ///`certificate_thumb_print`)
        ///VALUES.
        /// </summary>
        public static string InsertMapping {
            get {
                return ResourceManager.GetString("InsertMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ON DUPLICATE KEY UPDATE `sequence` = VALUES(`sequence`);
        ///.
        /// </summary>
        public static string InsertMappingOnDuplicateKey {
            get {
                return ResourceManager.GetString("InsertMappingOnDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to (@a{0},
        ///@b{0},
        ///@c{0}).
        /// </summary>
        public static string InsertMappingValueFormatString {
            get {
                return ResourceManager.GetString("InsertMappingValueFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  INSERT INTO `dns_record_mx_tls_profile_2`
        ///(`id`,`mx_record_id`,
        ///`end_date`,
        ///`failure_count`,
        ///`test1_tls_version`,
        ///`test1_cipher_suite`,
        ///`test1_curve_group`,
        ///`test1_signature_hash_alg`,
        ///`test1_error`,
        ///`test2_tls_version`,
        ///`test2_cipher_suite`,
        ///`test2_curve_group`,
        ///`test2_signature_hash_alg`,
        ///`test2_error`,
        ///`test3_tls_version`,
        ///`test3_cipher_suite`,
        ///`test3_curve_group`,
        ///`test3_signature_hash_alg`,
        ///`test3_error`,
        ///`test4_tls_version`,
        ///`test4_cipher_suite`,
        ///`test4_curve_group`,
        ///`test4_signa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsertRecord {
            get {
                return ResourceManager.GetString("InsertRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ON DUPLICATE KEY UPDATE `end_date` = VALUES(`end_date`),
        ///`failure_count` = VALUES(`failure_count`),
        ///`last_checked` = UTC_TIMESTAMP();
        ///SELECT LAST_INSERT_ID();.
        /// </summary>
        public static string InsertRecordOnDuplicateKey {
            get {
                return ResourceManager.GetString("InsertRecordOnDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  (@a{0},
        ///@b{0},
        ///@c{0},
        ///@d{0},
        ///@e{0},
        ///@f{0},
        ///@g{0},
        ///@h{0},
        ///@i{0},
        ///@j{0},
        ///@k{0},
        ///@l{0},
        ///@m{0},
        ///@n{0},
        ///@o{0},
        ///@p{0},
        ///@q{0},
        ///@r{0},
        ///@s{0},
        ///@t{0},
        ///@u{0},
        ///@v{0},
        ///@w{0},
        ///@x{0},
        ///@y{0},
        ///@z{0},
        ///@aa{0},
        ///@ab{0},
        ///@ac{0},
        ///@ad{0},
        ///@ae{0},
        ///@af{0},
        ///@ag{0},
        ///@ah{0},
        ///@ai{0},
        ///@aj{0},
        ///@ak{0},
        ///@al{0},
        ///@am{0},
        ///@an{0},
        ///@ao{0},
        ///@ap{0},
        ///@aq{0},
        ///@ar{0},
        ///@as{0},
        ///@at{0},
        ///@au{0},
        ///@av{0},
        ///@aw{0},
        ///@ax{0},
        ///@ay{0},
        ///@az{0},
        ///@ba{0},
        ///@bb{0},
        ///@bc{0},
        ///@bd{0},
        ///@be{0},
        ///@bf{0},
        ///@bg{0},
        ///@bh{0} [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsertRecordValueFormatString {
            get {
                return ResourceManager.GetString("InsertRecordValueFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  SELECT 
        ///    temp.domain_id,
        ///    temp.domain_name,
        ///    mx.id AS &apos;mx_record_id&apos;,
        ///    mx.hostname AS &apos;mx_record_hostname&apos;,
        ///    tls.id AS &apos;tls_security_profile_id&apos;,
        ///    tls.failure_count as &apos;failure_count&apos;,
        ///	tls.test1_tls_version as &apos;test1_tls_version&apos;,
        ///	tls.test1_cipher_suite as &apos;test1_cipher_suite&apos;,
        ///	tls.test1_curve_group as &apos;test1_curve_group&apos;,
        ///	tls.test1_signature_hash_alg as &apos;test1_signature_hash_alg&apos;,
        ///	tls.test1_error as &apos;test1_error&apos;,
        ///	tls.test2_tls_version as &apos;test2_tls_version&apos;,
        ///	tls.test2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectSecurityProfilesToUpdate {
            get {
                return ResourceManager.GetString("SelectSecurityProfilesToUpdate", resourceCulture);
            }
        }
    }
}
